# Generated by Django 4.2.7 on 2024-05-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchase_order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='items',
            field=models.CharField(max_length=200),
        ),
    ]
